---
driver:
  name: vagrant

  network:
  - [ "forwarded_port", { guest: 8081, host: 8081, auto_correct: true } ]

provisioner:
  name: chef_zero
  require_chef_omnibus: '14.4.56'

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[nginx-test-cookbook]
  attributes:
